### ISSUE TITLE
IndexError when No migrations : True

### ISSUE THREAD

**Issue by alexnater** [ctlab/GADMA#4]
Disabling migration results in the following error:
Traceback (most recent call last):
  File "/anaconda3/envs/gadma/lib/python2.7/site-packages/gadma-1.0.0-py2.7.egg/gadma/core.py", line 44, in run_genetic_algorithm
    ga_instance.run(shared_dict=shared_dict)
  File "/anaconda3/envs/gadma/lib/python2.7/site-packages/gadma-1.0.0-py2.7.egg/gadma/genetic_algorithm.py", line 719, in run
    self.print_and_draw_best_model()
  File "/anaconda3/envs/gadma/lib/python2.7/site-packages/gadma-1.0.0-py2.7.egg/gadma/genetic_algorithm.py", line 470, in print_and_draw_best_model
    support.print_model_code(self.out_dir, model, self.params, prefix=prefix + 'best_' + best_by.lower() + '_model')
  File "/anaconda3/envs/gadma/lib/python2.7/site-packages/gadma-1.0.0-py2.7.egg/gadma/support.py", line 403, in print_model_code
    os.path.join(moments_out_dir, prefix + '_moments_code' + suffix + '.py'))
  File "/anaconda3/envs/gadma/lib/python2.7/site-packages/gadma-1.0.0-py2.7.egg/gadma/demographic_model.py", line 2204, in moments_code_to_file
    par_labels[ms_index + 1] + ', 0]])\n')
IndexError: list index out of range

Error: GA number 1: list index out of range

**Comment by noscode** [comment]
Thank you, @alexnater!
Sorry for so long reply, I have fixed the bug in new [commit](https://github.com/ctlab/GADMA/commit/acdecc630734ea53f22e8cca9b58aa099d83f9a4).
