### ISSUE TITLE
Error - Set Nanc value for translation

### ISSUE THREAD

**Issue by alexsanyum** [ctlab/GADMA#66]
Hi again, 

I am trying to use gadma with a new dataset but I have this error when the program starts to find models. 

I really appreciate your help. 

[000:01:00]
All best by log-likelihood models
Number	log-likelihood	Model
UserWarning: Additional evaluation for theta. Nothing to worry if this warning is seldom. (/usr/local/lib/python3.8/dist-packages/gadma/engines/dadi_moments_common.py:138)
Traceback (most recent call last):
  File "/usr/local/bin/gadma", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/gadma/core/core.py", line 145, in main
    print_runs_summary(start_time, shared_dict, settings_storage)
  File "/usr/local/lib/python3.8/dist-packages/gadma/core/draw_and_generate_code.py", line 257, in print_runs_summary
    x_translated = engine.model.translate_values(
  File "/usr/local/lib/python3.8/dist-packages/gadma/models/demographic_model.py", line 143, in translate_values
    tr_value = var.translate_value_into(units=units,
  File "/usr/local/lib/python3.8/dist-packages/gadma/utils/variables.py", line 280, in translate_value_into
    raise ValueError("Set Nanc value for translation")
ValueError: Set Nanc value for translation

**Comment by noscode** [comment]
Hello @alexsanyum,

That is just a simply bug in GADMA right now. The solution is to set `Relative parameters` option to `True` in your parameters file. Please see #64 for more information and feel free to ask further questions!

Ekaterina

**Comment by alexsanyum** [comment]
Hello, 

It works. I generated an extra parameter file with just that option and resumed the previous gadma run and works perfectly.

I really appreciate your assistance <3

Greetings, 
Alex

**Comment by noscode** [comment]
You are welcome!
