### ISSUE TITLE
MomentsLD — ValueError: Can specify only recombination or bp bins, not both

### ISSUE THREAD

**Issue by James-S-Santangelo** [ctlab/GADMA#67]
Hey Ekaterina,

I'm trying to run some two-population demographic using the `momentsLD` engine and am getting the following traceback:

```
Traceback (most recent call last):                                                                                                                                                 
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/multiprocessing/pool.py", line 125, in worker                                                                               
    result = (True, func(*args, **kwds))
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/site-packages/gadma/engines/moments_ld_engine.py", line 30, in _read_data_one_job
    moments.LD.Parsing.compute_ld_statistics(
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/site-packages/moments/LD/Parsing.py", line 1259, in compute_ld_statistics
    raise ValueError("Can specify only recombination or bp bins, not both")
ValueError: Can specify only recombination or bp bins, not both
"""                                         

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/santang3/.conda/envs/gadma/bin/gadma", line 10, in <module>
    sys.exit(main())                        
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/site-packages/gadma/core/core.py", line 69, in main
    settings_storage.read_data()
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/site-packages/gadma/cli/settings_storage.py", line 891, in read_data
    engine.data = self.data_holder
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/site-packages/gadma/engines/engine.py", line 209, in data
    self.set_data(new_data)
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/site-packages/gadma/engines/engine.py", line 191, in set_data
    self.inner_data = self.read_data(data)
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/site-packages/gadma/engines/engine.py", line 121, in read_data
    return cls._read_data(data_holder)
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/site-packages/gadma/engines/moments_ld_engine.py", line 185, in _read_data
    region_stats = cls._get_region_stats(data_holder)
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/site-packages/gadma/engines/moments_ld_engine.py", line 171, in _get_region_stats
    result = pool.map(_read_data_one_job, all_kwargs)
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value                       
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/site-packages/gadma/engines/moments_ld_engine.py", line 30, in _read_data_one_job
    moments.LD.Parsing.compute_ld_statistics(
  File "/home/santang3/.conda/envs/gadma/lib/python3.8/site-packages/moments/LD/Parsing.py", line 1259, in compute_ld_statistics
    raise ValueError("Can specify only recombination or bp bins, not both")
```

Any idea what might be going on here? Here is my parameters file, which I modified from the example given here on on GitHub:

```
Input data : ./CM019101.1_4fold.vcf, ./pops.txt
Engine : momentsLD
initial_structure: 2,1
Output directory : gadma_momentsLD_results
ancestral_size_as_parameter: True
recombination_maps: ./maps
Mutation rate: 1.2e-8
Number of repeats : 10
Number of processes : 10
draw_models_every_n_iteration: 100
region_len: 2000000
ld_kwargs: {"report": True}
Sequence_length: 11067652
```

For context, I'm testing this out using a single chromosome with ~34K 4-fold sites. I have a genetic map for the chromosome in the `./maps` folder, the first few lines of which look like:

```
pos Map(cM)
16995   0
17012   3.139587207101613e-5
17063   1.2558348829472266e-4
19371   0.004388034826302345
19415   0.004469294730494511
```

Thanks for your help!

James

**Comment by noscode** [comment]
Dear James,

Thank you for the feedback! Fortunately, that is not your mistake (your files look totally fine!) but just the last update of `moments`. I have known about that bug for a while and I am finally finishing the fix. Today (as soon as tests will finish) there will be a new version of GADMA that fix this problem. Sorry for the delay!

Best regards,
Ekaterina

**Comment by James-S-Santangelo** [comment]
Dear Ekaterina, 

Thanks for the quick reply! I poked around a little bit and suspected the issue might have been with moments itself, but didn't have time to do a deep dive. Thanks for looking into this, and I look forward to working with the new update!

Sincerely,
James

**Comment by noscode** [comment]
Dear James.

You are welcome! The release is out so feel free to check it out and tell me if something is not working.

Best regards,
Ekaterina
