### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by anubhabkhan** [ctlab/GADMA#70]
Hey,

I am new to GADMA. I have installed GADMA2 and trying to run it on vcf file but I get the error pasted bellow. Could you please help. My parameter file is attached too.

UserWarning: Parameters will be in genetic units (Relative parameters). Engines dadi and moments require mutation rate and sequence length for unit translation (/usr/local/lib/python3.6/site-packages/gadma/cli/settings_storage.py:1352)
Data reading
False
Traceback (most recent call last):
  File "/usr/local/bin/gadma", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/gadma/core/core.py", line 69, in main
    settings_storage.read_data()
  File "/usr/local/lib/python3.6/site-packages/gadma/cli/settings_storage.py", line 891, in read_data
    engine.data = self.data_holder
  File "/usr/local/lib/python3.6/site-packages/gadma/engines/engine.py", line 209, in data
    self.set_data(new_data)
  File "/usr/local/lib/python3.6/site-packages/gadma/engines/engine.py", line 191, in set_data
    self.inner_data = self.read_data(data)
  File "/usr/local/lib/python3.6/site-packages/gadma/engines/engine.py", line 121, in read_data
    return cls._read_data(data_holder)
  File "/usr/local/lib/python3.6/site-packages/gadma/engines/dadi_moments_common.py", line 58, in _read_data
    data = read_vcf_data(cls.base_module, data_holder)
  File "/usr/local/lib/python3.6/site-packages/gadma/engines/dadi_moments_common.py", line 733, in read_vcf_data
    flanking_info=[None, None],
  File "/usr/local/lib64/python3.6/site-packages/moments/Misc.py", line 562, in make_data_dict_vcf
    g1, g2 = gt[0], gt[2]
IndexError: string index out of rang
[GADMA_param_HiC_scaffold_1.txt](https://github.com/ctlab/GADMA/files/9010375/GADMA_param_HiC_scaffold_1.txt)
e

**Comment by noscode** [comment]
Hi @anubhabkhan ,

Sorry for the late reply. The error occurs during VCF data reading. `Moments` sometimes failed to read files. Let's find out what is the reason and I think that I will put some warning for the future.
I have checked `moments` code and it looks like you have VCF file with haploid samples. Is that correct? Do you have GT field like `./.` or just `.`, where `.` is for 0 or 1?

Best regards,
Ekaterina

**Comment by anubhabkhan** [comment]
Hey,

My populations are diploid. I do have a GT field. I am attaching a sample of my vcf in .txt format here. Could you please take a look. It would be very helpful.

Thank you

[pop_order.txt](https://github.com/ctlab/GADMA/files/9035404/pop_order.txt)
[test.vcf.txt](https://github.com/ctlab/GADMA/files/9035405/test.vcf.txt)
.

**Comment by anubhabkhan** [comment]
Hey,

thanks for that. We have removed those loci but now we get a different error and I am unable to solve this one too. Could you please look at the attached files and advice.

Anubha
[GADMA.log](https://github.com/ctlab/GADMA/files/9140418/GADMA.log)
b

**Comment by noscode** [comment]
Hi Anubhab,

Great! I see that file was successfully read. The error is caused because GADMA tries to build model using `moments` engine for more than 5 populations. How many population have you specified in popmap file?
Usually GADMA supports up to three populations. It could deal with 4 and 5 but it is slow and I recommend to specify simple models (e.g. without migrations).

Best,
Ekaterina

**Comment by anubhabkhan** [comment]
Thanks so much. I tried with 6 populations and that is probably the reason it failed. I will try again with fewer populations. Thanks

Anubhab

**Comment by noscode** [comment]
You are welcome!
